version: '3.7'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db_network
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  api:
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=False
      - DATABASE_URL=postgresql://admin:admin@db:5432/postgres
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://admin:admin@localhost:5432/postgres
    links:
      - db:db
    volumes:
      - .:/code:z
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network
    depends_on:
      - api

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
