version: '3.7'

services:
  db:
    image: postgres:10-alpine
    env_file:
      - config/db/database_env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    build: .
    command: ./mask_detection/manage.py runserver 0.0.0.0:7000
    links:
      - db:db
    volumes:
      - .:/code:z
    ports:
      - 7000:7000
    depends_on:
      - db

volumes:
  db_volume: {}

